### ISSUE TITLE
Response.ren de r

### ISSUE THREAD

**Issue by billho** [zhegexiaohuozi/SeimiCrawler#38]
java.lang.IllegalAccessException: Class cn.wanghaomiao.seimi.core.SeimiBeanResolver can not access a member of class app.model.Activity with modifiers ""
at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Field.set(Field.java:761)
	at cn.wanghaomiao.seimi.core.SeimiBeanResolver.parse(SeimiBeanResolver.java:56)
	at cn.wanghaomiao.seimi.struct.Response.render(Response.java:156)
	at app.crawlers.Basic.start(Basic.java:61)

**Comment by billho** [comment]
cn.wanghaomiao.seimi.core.SeimiBeanResolver.java
line 56:
多线程这么玩必然会报错阿.
....
 _boolean accessFlag = f.isAccessible();_
                f.setAccessible(true);
                f.set(bean, defaultCastToTargetValue(target, f, res));
                _f.setAccessible(accessFlag);_
....

**Comment by zhegexiaohuozi** [comment]
`ReflectionUtils.doWithFields`的实现用了缓存，这里确实疏忽了，下个版本会修复。
